#!/usr/bin/env perl
#
# ogma: A featureful terminal speed-reading tool using RSVP (Rapid Serial Visual Presentation) based on speedread.
#
# Show input text as a per-word RSVP (rapid serial visual presentation)
# aligned on optimal reading points.  This kind of input mode allows
# reading text at a much more rapid pace than usual as the eye can
# stay fixed on a single place.
#
# Original work (c) Petr Baudis <pasky@ucw.cz> 2014
# Original work licensed under MIT License (see LICENSE.MIT)
#
# Modifications and additions (c) Aindréas Ó hAodha <aindreas@ohaodha.ie> 2025 
# Modifications licensed under GPL v3 (see LICENSE.GPL)
#
# This combined work is distributed under GPL v3.
#
# Usage: ogma [-w WORDSPERMINUTE] [-r RESUMEPOINT] [-m] [-b] file.txt

use warnings;
use strict;
use autodie;
use v5.14;

use utf8;
binmode(STDIN, ":encoding(UTF-8)");
binmode(STDOUT, ":encoding(UTF-8)");

use Term::ANSIColor;
use Term::ReadKey;
use POSIX qw(ceil floor);
use Time::HiRes qw(time sleep gettimeofday tv_interval);
use Getopt::Long;
use TOML::Tiny qw(from_toml);

my %defaults = (
    wpm          => 250,
    resume       => 0,
    multiword    => 0,
    bionic       => 0,
    wordtime     => 0.9,
    lentime      => 0.04,
    commatime    => 2,
    fstoptime    => 3,
    multitime    => 1.2,
    firsttime    => 0.2,
    filehandlers => [],
);

sub load_config {
    my $config_file_path = ($ENV{XDG_CONFIG_HOME} // "$ENV{HOME}/.config") . "/ogma/config.toml";
    my %config = %defaults;

    if (-f $config_file_path) {
        open(my $config_file, '<:encoding(UTF-8)', $config_file_path);
        my $toml = do { local $/; <$config_file> };
        close($config_file);

        my ($parsed, $parse_error) = from_toml($toml);

        if ($parse_error) {
            die("Error parsing config file: $parse_error\n");
        }

        if (my $timing_config = $parsed->{timing}) {
            for my $key (qw(wpm wordtime lentime commatime fstoptime multitime firsttime)) {
                $config{$key} = $timing_config->{$key} if defined $timing_config->{$key};
            }
        }

        if (my $display_config = $parsed->{display}) {
            for my $key (qw(multiword bionic)) {
                $config{$key} = $display_config->{$key} ? 1 : 0 if defined $display_config->{$key};
            }
        }

        if (my $filehandlers = $parsed->{filehandler}) {
            $config{filehandlers} = $filehandlers;
        }
    }

    return \%config;
}

my $config = load_config();

GetOptions(
    "wpm|w=i"     => \$config->{wpm},
    "resume|r=i"  => \$config->{resume},
    "multiword|m" => \$config->{multiword},
    "bionic|b"    => \$config->{bionic},
);

my $paused = 0;
my $next_word_time = 0;
my $next_input_time = 0;

my @lastlines;
my ($term_width, $term_height);
my $center_row;
my $center_col;

my $wordcounter = 0;
my $lettercounter = 0;
my $total_words = 0;  # Total words in document
my $t0 = [gettimeofday];

# Terminal state management
sub init_terminal {
    # Redirect stdin to /dev/tty for keyboard input
    # (file input will come from command line arg or pipe before this)
    open(my $tty, '<', '/dev/tty') or die "Cannot open /dev/tty: $!";
    *STDIN = $tty;

    ReadMode('cbreak');

    update_terminal_size();
    clear_screen();
    hide_cursor();
}

sub cleanup_terminal {
    show_cursor();
    clear_screen();
    ReadMode('restore');
}

sub update_terminal_size {
    ($term_width, $term_height) = GetTerminalSize();
    $center_row = int($term_height / 2);
    $center_col = int($term_width / 2);
}

sub clear_screen {
    print "\033[2J";
}

sub hide_cursor {
    print "\033[?25l";
}

sub show_cursor {
    print "\033[?25h";
}

sub move_cursor {
    my ($row, $col) = @_;
    print "\033[${row};${col}H";
}

sub clear_line {
    print "\033[2K";
}

sub show_guide {
    move_cursor($center_row - 1, $center_col);
    print color('red') . "v" . color('reset');
}

sub show_word {
    my ($word, $orp) = @_;

    # Clear the lines we'll use
    move_cursor($center_row, 1);
    clear_line();

    my $pivotch = substr($word, $orp, 1);
    $pivotch = "·" if $pivotch eq ' ';

    # Calculate starting column so ORP is at center
    my $word_start_col = $center_col - $orp;

    move_cursor($center_row, $word_start_col);

    # Display word with formatting
    print color("bold") . substr($word, 0, $orp)
        . color("red") . $pivotch . color("reset")
        . ($config->{bionic} ? "" : color("bold"))
        . substr($word, $orp+1)
        . color("reset");
}

sub show_progress {
    my $bottom_row = $term_height;

    # Bottom left: Speed and status
    move_cursor($bottom_row, 1);
    clear_line();
    print "$config->{wpm} wpm";

    if ($paused) {
        print "  " . color("yellow") . "PAUSED" . color("reset");
    }

    if ($config->{multiword}) {
        print "  " . color("cyan") . "[multi]" . color("reset");
    }

    if ($config->{bionic}) {
        print "  " . color("cyan") . "[bionic]" . color("reset");
    }

    # Bottom center: Progress bar (if we know total words)
    if ($total_words > 0) {
        my $progress_width = int($term_width * 0.4);  # 40% of screen width
        my $progress_start = int($term_width / 2) - int($progress_width / 2);

        my $percent = $wordcounter / $total_words;
        my $filled = int($percent * $progress_width);

        move_cursor($bottom_row, $progress_start);
        print color('green');
        print "█" x $filled;
        print color('dark white');
        print "░" x ($progress_width - $filled);
        print color('reset');

        # Show percentage
        my $pct_text = sprintf(" %d%% ", int($percent * 100));
        my $pct_col = $progress_start + $progress_width + 2;
        move_cursor($bottom_row, $pct_col);
        print $pct_text;
    }

    # Bottom right: Word count
    my $count_text = sprintf("Word %d", $wordcounter + $config->{resume});
    if ($total_words > 0) {
        $count_text .= sprintf("/%d", $total_words + $config->{resume});
    }
    move_cursor($bottom_row, $term_width - length($count_text) - 1);
    print $count_text;
}

sub print_context {
    my (@words, $index) = @_;
}

# sub print_context {
#     my ($wn) = @_;
#
#     # Show context lines above the word
#     if ($lastlines[1]) {
#         move_cursor($center_row - 3, 1);
#         clear_line();
#         # Truncate if too long for screen
#         my $line = $lastlines[1];
#         $line = substr($line, 0, $term_width - 2) if length($line) > $term_width - 2;
#         print $line;
#     }
#
#     if ($lastlines[0]) {
#         move_cursor($center_row - 2, 1);
#         clear_line();
#
#         my $line0 = $lastlines[0];
#         $line0 = substr($line0, 0, $term_width - 2) if length($line0) > $term_width - 2;
#
#         # Highlight current word in context
#         $line0 =~ s/^((?:.*?(?:-|\s)+){$wn})(.*?)(-|\s)/$1 . colored($2, 'yellow') . $3/e;
#         print $line0;
#     }
# }

sub find_ORP {
    my ($word) = @_;
    return 4 if (length($word) > 13);
    return (0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3)[length($word)];
}

sub word_time {
    my ($word) = @_;

    my $time = $config->{wordtime};
    if ($word =~ /[.?!]\W*$/) {
        $time = $config->{fstoptime};
    } elsif ($word =~ /[:;,]\W*$/) {
        $time = $config->{commatime};
    } elsif ($word =~ / /) {
        $time = $config->{multitime};
    }
    $time += sqrt(length($word)) * $config->{lentime};
    $time *= 60 / $config->{wpm};

    $time = $config->{firsttime} if ($wordcounter == 0 and $time < $config->{firsttime});

    return $time;
}

sub process_keys {
    my ($word, $orp, $word_index) = @_;

    while (defined(my $ch = ReadKey(-1))) {  # -1 = non-blocking
        if ($ch eq '[') {
            $config->{wpm} -= 10;

        } elsif ($ch eq ']') {
            $config->{wpm} += 10;

        } elsif ($ch eq 'b') {
            $config->{bionic} = !$config->{bionic};

        } elsif ($ch eq 'm') {
            $config->{multiword} = !$config->{multiword};

        } elsif ($ch eq ' ') {
            $paused = !$paused;
            if ($paused) {
                print_context($word_index);
                show_guide();
                show_word($word, $orp);
            } else {
                $next_word_time = time();
                # Clear context lines
                move_cursor($center_row - 3, 1);
                clear_line();
                move_cursor($center_row - 2, 1);
                clear_line();
            }

        } elsif ($ch eq 'q') {
            print_stats();
            exit;
        }
    }
    return '';
}

sub print_stats {
    my $elapsed = tv_interval($t0, [gettimeofday]);
    my $truewpm = $wordcounter / $elapsed * 60;

    cleanup_terminal();

    printf("\n%.2fs, %d words, %d letters, %s%.2f%s true wpm\n",
        $elapsed, $wordcounter, $lettercounter,
        color('bold green'), $truewpm, color('reset'));
}

$SIG{INT} = sub {
    print_stats();
    my $resume_word = $wordcounter + $config->{resume};
    say " To resume from this point run with argument -r $resume_word";
    exit;
};

$SIG{WINCH} = sub {
    update_terminal_size();
    clear_screen();
    show_guide();
};

sub read_words {
    my $filename = $ARGV[0];
    my @lines;

    if (-f $filename) {
        @lines = <>;
    }

    if ($filename) {
        for my $handler (@{$config->{filehandlers}}) {
            if ($filename =~ /$handler->{regex}/) {
                my $cmd = "$handler->{command}";
                $cmd =~ s/%f/$filename/g;

                open(my $input, '-|', "$cmd")
                    or die "Failed to run filehandler for $filename\n";
                @lines = <$input>;
                close($input);
                last;
            }
        }
    }

    my @words = grep { length } map { split /\s+/ } @lines;

    return(@words);
}

sub main {
    my @words = read_words();
    $total_words = scalar(@words);

    init_terminal();
    clear_screen();
    show_guide();
    show_progress();

    $next_word_time = time();
    $next_input_time = time();

    for (my $index = 0; $index <= $#words; $index++) {
        my $word = $words[$index];
        my $orp = find_ORP($word);

        if ($config->{multiword}) {
            if (length($word) < 3 and length($words[$index+1]) < 3) {
                $word = $word . " " . $words[$index+1];
                $index++;
            }
        }

        while (1) {
            my $current_time = time();

            if ($next_word_time <= $current_time and !$paused) {
                $next_word_time += word_time($words[$index+1]);

                $wordcounter++;
                $lettercounter += length($word);

                last;
            }

            if ($next_input_time <= $current_time) {
                process_keys($word, $orp, $index);
                $next_input_time += 0.05;
            }

            show_word($word, $orp);
            show_progress();

            my $sleep_time = ($next_word_time < $next_input_time and !$paused) 
                ? $next_word_time - $current_time 
                : $next_input_time - $current_time;
            sleep($sleep_time) if ($sleep_time > 0);
        }
    }

    print_stats();
}

main();
